language: java

dist: trusty

jdk:
  - openjdk7
  - oraclejdk8

before_install:
  - chmod +x ./.travis/maven-build.sh
  - chmod +x ./.travis/call-creation.sh
  - mvn clean

install:
  - sudo apt-get update && sudo apt-get --assume-yes install zip unzip

script: "./.travis/maven-build.sh"

after_deploy: "./.travis/call-creation.sh"

notifications:
  email: false
  slack:
    secure: uTkEvscGsgyi9iFjJW+2lAsjonKdCJoHemvVORKX7c/awjjhIpoqWFjsWClut0hYLTeoTBYKsZR6ZPJ7uRHG5oawlwW+LNz3paRGICGJGzD9L5cGGsRGEznAXPnRDlen1Aii5xcTHS3EGaZwZwwmns6K/hhjG7kYuD5X3XGCtd4+EC52O7zf3ZB3FAUC3FBHayMidAYzrDEqWG9R+3sziKadADX+PIREFYqZcBE4xZUtza0MV2O6PJ/DZmpR/qC7socaxOEUTLC6fEmPaEiQyjKshcUFw0V9oOYyw5ysNTEf6dwEM4AT2DzydVsMB8PxE+o50i2X8McajxYmsDZbu2UsyxXsNI7lur4Ob2ET7tXWjr0Kn3ZPFQ7yEFML29HOQfNdPp1rj9kebncGf0Rghu6mhuVcjDPEABMKKtVUBjCrQkyKgUNNiXC3BphMiFL6gkCcLnBVbDHkv751R+5tAwalgEiOUVolCkz0UJjuYq87VO1fJhQGls5FLPbmnLJ2Zc+3D2pnUq6RZ3aI4TTv7FhIrk9qybv4Xox6kTmTvKqEDP89APg23dualkeZh/aKgDCkEkwbJTHU3dmYvbRsekpjGg88BbwRIR1591wpAs2gyLRZ0Dy5uTYrMo8IhWS+XNduFEsEOcOgm64xNj24MevV0Sgn6DdpjUt6jtL09ho=
  webhooks:
    on_success: always
    on_failure: always
    on_start: never

env:
  global:
    - PROVIDER_VERSION=2.0.1

cache:
  directories:
    - ".autoconf"
    - "$HOME/.m2"

deploy:
  - provider: s3
    access_key_id: AKIAJDZLZNH2PIKHUKOA
    secret_access_key:
      secure: BNwTSh+mwS+6E9BKw1+FZEvWlWzDIOmXxvLu8mbqe5SnpYoKlfHbkUIZIn5WHJn6Mh0yxtC9/vR7cjnILM5lYXxecN5Vp4wa7pYpX2+dT1RMw6qPtzvQFGQbXH5eoGXx0tBg/9SPtJkRyufpBrkixuIwDHk45F/0n/JxG2RvWf3icY3j9PWUZmRPOChk5CqfPhj9dDNTBxgekUQkpgcq9lnp3gObyF2yxNupRYvpMO7aZrm5Xgm2TuvG996CYyvrG2pKm/Xptw3ZOPtErDmfXPwcx1mMeBcKLC7C9jU0HnUfPIfOGA46fjD8hPbdqzeoxwuOWiSmrChvfZVxKFeOZmdCgXAOXRv+DROEq1WOFVgPy60FIcDQyGbZrZTyv4pOulnPCHOWsmqrTDuJcnZvUV3Gk4phijk8byc6pysazYeaXyQxwXH/dL6QOHzqLpqiwS6JrtToD1/rErgj9fkUM3UHQkyTTGBlhk5uVOy5PEabIXK0hJ+5MDE0s4s3qAFfEGUZBSE0svLc/4lvxGe1Q3pYbP8vhmXSnDGX+JllmUQnfSEneQgdt10pvKsOBAv+8ar8b/k/yxmfJHHeFKqAO1BDnEET8yDri26YPz/a0zL2GR6zSHpFjhjO6T1XDfmmFcCNKVOBVPrv+SG5q8GHBIKxOzmBLSN37K6xu+FYSew=    bucket: parabot
    skip_cleanup: true
    local-dir: "./target/final/"
    upload-dir: artifacts/runewild-provider
    region: us-west-1
    detect_encoding: true
    acl: public_read
    on:
      repo: Parabot/Parabot-317-API-Minified-RuneWild
      branch:
        - master
        - development
      jdk: 'openjdk7'
